spring:
  config:
     activate:
        on-profile: dev
  datasource:
    url: jdbc:h2:mem:jcart;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
